baseURL = "https://leoczech.cz/"
relativeURLs = true
title = "LeoCzech spol. s r.o."

defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = false
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true

[languages.cs]
  label = "Česky"
  weight = 1
  contentDir = "content/cs"

  [[languages.cs.menus.main]]
    name = "Úvod"
    url = "/"
    weight = 1
  [[languages.cs.menus.main]]
    name = "O nás"
    url = "/o-nas/"
    weight = 2
  [[languages.cs.menus.main]]
    name = "Papírový lev"
    url = "/soutez/"
    weight = 3
  [[languages.cs.menus.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

[languages.en]
  label = "English"
  weight = 2
  contentDir = "content/en"

  [[languages.en.menus.main]]
    name = "Home"
    url = "/en/"
    weight = 1
  [[languages.en.menus.main]]
    name = "About"
    url = "/en/about/"
    weight = 2
  [[languages.en.menus.main]]
    name = "Paper Lion"
    url = "/en/contest/"
    weight = 3
  [[languages.en.menus.main]]
    name = "Contact"
    url = "/en/contact/"
    weight = 4

[languages.de]
  label = "Deutsch"
  weight = 3
  contentDir = "content/de"

  [[languages.de.menus.main]]
    name = "Start"
    url = "/de/"
    weight = 1
  [[languages.de.menus.main]]
    name = "Über uns"
    url = "/de/ueber-uns/"
    weight = 2
  [[languages.de.menus.main]]
    name = "Papierlöwe"
    url = "/de/wettbewerb/"
    weight = 3
  [[languages.de.menus.main]]
    name = "Kontakt"
    url = "/de/kontakt/"
    weight = 4
