name = "email-to-issue"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_OWNER = "rjicha"
GITHUB_REPO = "leoczech"

[[send_email]]
name = "SEND_EMAIL"
